---
language: python
sudo: required

env:
    # - distro: debian8 
    # init: /lib/systemd/systemd
    # run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    # use_python3: True
    # - distro: ubuntu1604
    # init: /lib/systemd/systemd
    # run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    # use_python3: True
  - distro: debian8 
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    use_python3: False
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    use_python3: False

services:
  - docker

before_install:
  # Pull container from Docker Hub.
  - 'sudo docker pull geerlingguy/docker-${distro}-ansible:latest'

install:
  # Create a random file to store the container ID.
  - container_id=$(mktemp)

  # Run container detached, with our role mounted inside.
  - 'sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'

  # Install dependencies.
  - 'sudo docker exec "$(cat ${container_id})" ansible-galaxy install -r /etc/ansible/roles/role_under_test/tests/requirements.yml'

script:
  # Test the syntax of the role files
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  # Test the role
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --extra-vars "use_python3=${use_python3}"'
    
  # Test role idempotence.
  - idempotence=$(mktemp)
  - 'sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --extra-vars "use_python3=${use_python3}" | tee -a ${idempotence}'
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test results of role
  #- 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ls -l /var/run/'
  #- 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm cat /var/log/supervisord/*'
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm which supervisorctl'
  - version=$(mktemp)
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm supervisorctl version | tee -a ${version}'
  - grep "^\s*[0-9]\+\.[0-9]\+\.[0-9]\+\s*$" ${version}

after_success:
  # Clean up.
  - 'sudo docker stop "$(cat ${container_id})"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
