---
- name: Pip install Supervisord 
  pip:
    name: supervisor
    state: present

- name: Create Group for Supervisord
  group:
    name: "{{ supervisord_group_name }}"
    state: present

- name: Create User for Supervisord
  user:
    name: "{{ supervisord_user_name }}"
    groups: "{{ supervisord_group_name }}"
    append: yes

- name: Create supervisord log directory
  file:
    path: "{{ supervisord_log_dir }}"
    state: directory
    owner: "{{ supervisord_user_name }}"
    group: "{{ supervisord_group_name }}"
    mode: 0775

- name: Create supervisord configuration directory
  file:
    path: "{{ supervisord_config_dir }}"
    state: directory
    owner: "{{ supervisord_user_name }}"
    group: "{{ supervisord_group_name }}"
    mode: 0775

- name: Create supervisord configured services directory
  file:
    path: "{{ supervisord_config_dir }}/conf.d"
    state: directory
    owner: "{{ supervisord_user_name }}"
    group: "{{ supervisord_group_name }}"
    mode: 0775

- name: Install supervisord.conf file
  template:
    src: supervisord.conf.j2
    dest: "{{ supervisord_config_dir }}/supervisord.conf"
    mode: 0755

- name: Install supervisord.system script
  template:
    src: supervisord.service.j2
    dest: /etc/systemd/system/supervisord.service
    mode: 0755
  notify: restart supervisord
