---
- name: Start supervisord (systemd)
  listen: "start supervisord"
  systemd:
    name: supervisord
    enabled: yes
    state: started
  when:
    - ansible_service_mgr == 'systemd'

- name: Start supervisord (upstart)
  listen: "start supervisord"
  service:
    name: supervisord
    enabled: yes
    state: started
  when:
    - ansible_service_mgr == 'upstart'

- name: Restart supervisord (systemd)
  listen: "restart supervisord"
  systemd:
    name: supervisord
    state: restarted
  when:
    - ansible_service_mgr == 'systemd'

- name: Restart supervisord (upstart)
  listen: "restart supervisord"
  service:
    name: supervisord
    state: restarted
  when:
    - ansible_service_mgr == 'upstart'

- name: Stop supervisord (systemd)
  listen: "stop supervisord"
  systemd:
    name: supervisord
    state: stopped
  when:
    - ansible_service_mgr == 'systemd'

- name: Stop supervisord (upstart)
  listen: "stop supervisord"
  service:
    name: supervisord
    state: stopped
  when:
    - ansible_service_mgr == 'upstart'
