---
- name: start supervisord
  service:
    name: supervisord
    enabled: yes
    state: started

- name: restart supervisord
  service:
    name: supervisord
    state: restarted

- name: stop supervisord
  service:
    name: supervisord
    state: stopped
