---
- name: start supervisord
  systemd:
    name: supervisord
    enabled: yes
    state: started

- name: restart supervisord
  systemd:
    name: supervisord
    state: restarted

- name: stop supervisord
  systemd:
    name: supervisord
    state: stopped
